FEAT:fixing

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -34,18 +34,18 @@ jobs:
           key: ${{ secrets.PRIVATE_KEY }}
           port: 22
           script: |
-            echo "==> DEPLOYING ON SERVER"
-            cd donation-app
-            git checkout development
-            git pull origin development
-            echo "==> CODE PULLED"
-
-            npm install
-            echo "==> DEPENDENCIES INSTALLED"
-
-            npm run build
-            echo "==> BUILD SUCCESSFUL"
-
-            pm2 stop donation || echo "PM2 process not found"
-            pm2 start dist/index.cjs --name donation
-            echo "==> APP STARTED WITH PM2"
+                echo "==> DEPLOYING ON SERVER"
+                cd donation-app
+                git checkout development
+                git pull origin development
+                echo "==> CODE PULLED"
+              
+                /root/.nvm/versions/node/v23.11.0/bin/npm install
+                echo "==> DEPENDENCIES INSTALLED"
+              
+                /root/.nvm/versions/node/v23.11.0/bin/npm run build
+                echo "==> BUILD SUCCESSFUL"
+              
+                /root/.nvm/versions/node/v23.11.0/bin/pm2 stop donation || echo "PM2 process not found"
+                /root/.nvm/versions/node/v23.11.0/bin/pm2 start dist/index.js --name donation
+                echo "==> APP STARTED WITH PM2"
